### ISSUE TITLE
Class 'Mvdstam\ArdentTranslatable\ArdentTranslatable' not found

### ISSUE THREAD

**Issue by k-zakhariy** [Pixelindustries/ardent-translatable#1]
HI, did anyone have this problem ?
![image](https://cloud.githubusercontent.com/assets/5267851/8021257/4bb1f46a-0ca1-11e5-9853-7d64d49b2b75.png)
This exception throw only when i deploy to production server, but localy all work fine, in the local environment i use WAMP. I was trying to change folder permissions but this not help me. Please help.

**Comment by mvdstam** [comment]
Hey @k-zakhariy, this package is no longer maintained/supported unfortunately. I highly recommend using FormRequests (as provided by Laravel 5) for data validation, which renders Ardent pretty much obsolete.

**Comment by k-zakhariy** [comment]
Thanks!
